### ISSUE TITLE
ensureLumigoPythonIsInstalled fails, but is listed in requirements.txt

### ISSUE THREAD

**Issue by maxfunke** [lumigo-io/serverless-lumigo-plugin#70]
Hi, I want to set up some manual tracing.
I followed the [guide](https://github.com/lumigo-io/serverless-lumigo-plugin#python-functions).
The lumigo_tracer package is listed in requerments.txt and is installed via `pip install -r requirements.txt`.
Still deploying with serverless framework does throw this TypeError that sais that Lumigo-Python-Package is not installed.
Are there any additional tweaks to be made?

``` bash
❯ sls deploy
Serverless: serverless-lumigo: there are 27 function(s) to wrap...
Serverless: serverless-lumigo: checking if lumigo_tracer is installed...

  Type Error ---------------------------------------------

  TypeError: plugins.includes is not a function
      at LumigoPlugin.ensureLumigoPythonIsInstalled (/Users/xxx/sls_plugins/node_modules/serverless-lumigo/src/index.js:329:38)
      at LumigoPlugin.wrapFunctions (/Users/xxx/sls_plugins/node_modules/serverless-lumigo/src/index.js:199:17)
      at LumigoPlugin.afterPackageInitialize (/Users/xxx/sls_plugins/node_modules/serverless-lumigo/src/index.js:71:14)
      at /usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:498:55
      at tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Object.gotValue (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/reduce.js:168:18)
      at Object.gotAccum (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/reduce.js:155:25)
      at Object.tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:461:21)

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.16.1
     Framework Version:         1.83.0
     Plugin Version:            3.8.4
     SDK Version:               2.3.2
     Components Version:        2.34.9

```

**Comment by efimk-lu** [comment]
Hey @maxfunke , is the `serverless.yml` contains nodejs and python lambdas or only python lambdas?

**Comment by maxfunke** [comment]
just python lambdas.

When I set this:
```yaml
custom:
  lumigo:
    token: xxx
    skipReqCheck: true
```

I can deploy (when not using the decorator).

But as soon as I actually use `@lumigo_tracer()` decorator in the code, it seems to interfere somehow, because deployment command stucks in the shell and nothing happens.

**Comment by nirLumigo** [comment]
Hi,
1. When serverless-lumigo-plugin is used there's no need to add `@lumigo_tracer(...)` in the code manually.
The purpose of serverless-lumigo-plugin is to allow tracing without changes in the code.

2. It looks like you added `skipReqCheck`. But you said "The lumigo_tracer package is listed in requerments.txt and is installed via pip install -r requirements.txt.", if this is the case then no need to pass `skipReqCheck: true`:
![image](https://user-images.githubusercontent.com/49228804/126336305-453b5526-016f-4034-98c4-30091bae7034.png)

3. If these changes won't solve the issue, can you attach you `plugins` section?

**Comment by maxfunke** [comment]
Hi @nirLumigo 

> 1. When serverless-lumigo-plugin is used there's no need to add `@lumigo_tracer(...)` in the code manually.
>    The purpose of serverless-lumigo-plugin is to allow tracing without changes in the code.

I tried to leave the decorator as I realised how the plugin works. Still I cannot deploy. The deploy command stucks without errors or helpful output.

> 2. It looks like you added `skipReqCheck`. But you said "The lumigo_tracer package is listed in requerments.txt and is installed via pip install -r requirements.txt.", if this is the case then no need to pass `skipReqCheck: true`:

The problem is, when I don't `skipReqCheck`, the error message above will be shown.

> 3. If these changes won't solve the issue, can you attach you `plugins` section?

I use a central lokal path for this project, since these modules are shared across multiple projects. I also tried to install the plugin locally but it did not help.
```yaml
plugins:
  localPath: ../../../sls_plugins/node_modules
  modules:
    - serverless-python-requirements
    - serverless-plugin-git-variables
    - serverless-prune-plugin
    - serverless-dynamodb-autoscaling
    - serverless-step-functions
    - serverless-lumigo
```

**Comment by efimk-lu** [comment]
@maxfunke , will changing the plugins section to

```
plugins:
    - serverless-python-requirements
    - ../../../sls_plugins/node_modules
    - serverless-plugin-git-variables
    - serverless-prune-plugin
    - serverless-dynamodb-autoscaling
    - serverless-step-functions
    - serverless-lumigo
```

work for you?

And now after fixing the docker issue are you able to use `skipReqCheck` successfully?

**Comment by nirLumigo** [comment]
Hi @maxfunke , I was able to reproduce the error and we're working on a fix.

**Comment by nirLumigo** [comment]
@maxfunke I released a new version, can you try it and verify that it works?
You should be able to remove `skipReqCheck: true`.

**Comment by maxfunke** [comment]
@nirLumigo 
yes, now the requirements check works.

```bash
Serverless: serverless-lumigo: there are 1 function(s) to wrap...
Serverless: serverless-lumigo: checking if lumigo_tracer is installed...
Serverless: serverless-lumigo: ensuring there is a requirement.txt or equivalent...
Serverless: Generated requirements from
```

using npm package `"serverless-lumigo": "1.12.6"`
I have installed the package not in project-root, but in a different directory `../../../sls_plugins/`(as above)

thank you
